---
- name: Package Installation and Configuration
  hosts: managed
  environment:
    PATH: "{{ discovered_path }}"
  tasks:
    - name: Deploy tmux configuration
      ansible.builtin.template:
        src: ../templates/tmux.conf.j2
        dest: "~/.tmux.conf"
        mode: '0644'
      when: tmux_path is defined

    - name: Ensure tmux is present at the defined path if specified
      ansible.builtin.stat:
        path: "{{ tmux_path }}"
      register: tmux_check
      when: tmux_path is defined
